FROM stmicro_base:latest
RUN mkdir -p ts_sdk_bldenv
COPY targets/stmicro/chipset/stm32l4 /ts_sdk_bldenv/stm32l4
ENV CHIPSET_MCU=$(CHIPSET_MCU)
ENV CHIPSET_OS=$(CHIPSET_OS)
CMD cp /ts_sdk_bldenv/stm32l4/chipset_hal/STM32Cube_FW_L4_V1.8.0/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_conf_template.h /ts_sdk_bldenv/stm32l4/chipset_hal/STM32Cube_FW_L4_V1.8.0/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_conf.h \
        && mkdir -p /build/stm32l4 \
	&& cd /ts_sdk_bldenv/stm32l4 && make clean && make all \
        && cp ./build/lib$CHIPSET_MCU.a /build/stm32l4/ \
        && (find chipset_hal/STM32Cube_FW_L4_V1.8.0/Drivers -name '*.h' | tar --create --files-from -) | (cd /build/stm32l4/ && tar xfp -) \
        && (find chipset_hal/STM32Cube_FW_L4_V1.8.0/Middlewares/Third_Party/FreeRTOS/Source/include/ -name '*.h' | tar --create --files-from -) | (cd /build/stm32l4/ && tar xfp -) \
        && (find chipset_hal/STM32Cube_FW_L4_V1.8.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/ -name '*.h' | tar --create --files-from -) | (cd /build/stm32l4/ && tar xfp -) \
        && (find chipset_hal/STM32Cube_FW_L4_V1.8.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/ -name '*.h' | tar --create --files-from -) | (cd /build/stm32l4/ && tar xfp -) \
        && cp chipset_hal/STM32Cube_FW_L4_V1.8.0/Projects/STM32L476RG-Nucleo/Templates/SW4STM32/STM32L476RG_NUCLEO/*.ld /build/stm32l4/
