FROM stmicro_base:latest
RUN mkdir -p ts_sdk_bldenv
COPY targets/stmicro/chipset /ts_sdk_bldenv/
COPY platform/sw/stm32f4 /ts_sdk_bldenv/
ENV CHIPSET_MCU=$(CHIPSET_MCU)
CMD cd /ts_sdk_bldenv/stm32f4 && make clean && make all \
        && mkdir -p /build/stm32f4 \
        && cp ./build/lib$CHIPSET_MCU.a /build/stm32f4/ \
        && (find . -name '*.h' -print | tar --create --files-from -) | (cd /build/stm32f4/ && tar xvfp -) \
        && cp ldscript/*.ld /build/stm32f4/
