FROM ubuntu:16.04
RUN apt-get update \
    && apt-get install -y vim \
    && apt-get install -y make \
    && apt-get install -y gcc-multilib \
    && apt-get install -y gcc \
    && apt-get install -y uuid
