FROM pi3_base:latest
RUN mkdir -p ts_sdk
COPY sdk /ts_sdk/sdk
COPY platform /ts_sdk/platform
COPY tools/config /ts_sdk/tools/config
COPY tools/scripts/config_build_env.sh /ts_sdk/tools/scripts/
RUN chmod a+x /ts_sdk/tools/scripts/config_build_env.sh
CMD cd /ts_sdk && \
    . tools/scripts/config_build_env.sh \
    && cd /ts_sdk/sdk/cloud_comm && make clean && make all
